In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# importing datasets
data_set = pd.read_csv('50_Startups.csv')
data_set.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
data_set.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [4]:
data_set.shape

(50, 5)

In [5]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data_set['State'] = label_encoder.fit_transform(data_set['State'])
print(data_set.head())

   R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [6]:
# onehot encoding is the process of creating dummy variable
# importing one hot encoder

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
onehotencoder_df = pd.DataFrame(onehotencoder.fit_transform(data_set[['State']]).toarray())

#merge
data_set = data_set.join(onehotencoder_df)
data_set.head()

   R&D Spend  Administration  Marketing Spend  State     Profit    0    1    2
0  165349.20       136897.80        471784.10      2  192261.83  0.0  0.0  1.0
1  162597.70       151377.59        443898.53      0  191792.06  1.0  0.0  0.0
2  153441.51       101145.55        407934.54      1  191050.39  0.0  1.0  0.0
3  144372.41       118671.85        383199.62      2  182901.99  0.0  0.0  1.0
4  142107.34        91391.77        366168.42      1  166187.94  0.0  1.0  0.0

In [7]:
onehotencoder_df

      0    1    2
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  0.0  1.0
4   0.0  1.0  0.0
5   0.0  0.0  1.0
6   1.0  0.0  0.0
7   0.0  1.0  0.0
8   0.0  0.0  1.0
9   1.0  0.0  0.0
10  0.0  1.0  0.0
11  1.0  0.0  0.0
12  0.0  1.0  0.0
13  1.0  0.0  0.0
14  0.0  1.0  0.0
15  0.0  0.0  1.0
16  1.0  0.0  0.0
17  0.0  0.0  1.0
18  0.0  1.0  0.0
19  0.0  0.0  1.0
20  1.0  0.0  0.0
21  0.0  0.0  1.0
22  0.0  1.0  0.0
23  0.0  1.0  0.0
24  0.0  0.0  1.0
25  1.0  0.0  0.0
26  0.0  1.0  0.0
27  0.0  0.0  1.0
28  0.0  1.0  0.0
29  0.0  0.0  1.0
30  0.0  1.0  0.0
31  0.0  0.0  1.0
32  1.0  0.0  0.0
33  0.0  1.0  0.0
34  1.0  0.0  0.0
35  0.0  0.0  1.0
36  0.0  1.0  0.0
37  1.0  0.0  0.0
38  0.0  0.0  1.0
39  1.0  0.0  0.0
40  1.0  0.0  0.0
41  0.0  1.0  0.0
42  1.0  0.0  0.0
43  0.0  0.0  1.0
44  1.0  0.0  0.0
45  0.0  0.0  1.0
46  0.0  1.0  0.0
47  1.0  0.0  0.0
48  0.0  0.0  1.0
49  1.0  0.0  0.0

In [8]:
data_set=data_set.drop(columns=[0])

In [9]:
data_set = data_set.drop(columns=['State'])

In [10]:
data_set.head()

   R&D Spend  Administration  Marketing Spend     Profit    1    2
0  165349.20       136897.80        471784.10  192261.83  0.0  1.0
1  162597.70       151377.59        443898.53  191792.06  0.0  0.0
2  153441.51       101145.55        407934.54  191050.39  1.0  0.0
3  144372.41       118671.85        383199.62  182901.99  0.0  1.0
4  142107.34        91391.77        366168.42  166187.94  1.0  0.0

In [11]:
x = data_set.drop(columns=['Profit'])

In [12]:
y = data_set['Profit']

In [13]:
# Splitting the dataset into training and test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [14]:
# Fitting the MLR model to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [15]:
#Predicting the Test set results
y_pred = regressor.predict(x_test)

In [16]:
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533012, 167921.0656955 ])

In [17]:
y_test

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
Name: Profit, dtype: float64

In [18]:
print('Train Score:',regressor.score(x_train,y_train))
print('Test Score:',regressor.score(x_test, y_test))

Train Score: 0.9501847627493607
Test Score: 0.9347068473282423

In [19]:
import statsmodels.api as sm

In [20]:
x = sm.add_constant(x)
  #(OR)
# x = nm.append(arr = nm.ones((50,1)).astype(int), values=x, axis=1)  
x.head()

e:\Users\venky\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

   const  R&D Spend  Administration  Marketing Spend    1    2
0    1.0  165349.20       136897.80        471784.10  0.0  1.0
1    1.0  162597.70       151377.59        443898.53  0.0  0.0
2    1.0  153441.51       101145.55        407934.54  1.0  0.0
3    1.0  144372.41       118671.85        383199.62  0.0  1.0
4    1.0  142107.34        91391.77        366168.42  1.0  0.0

In [22]:
# Fit OLS model
regressor_OLS =sm.OLS(y,x).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Fri, 16 Jul 2021   Prob (F-statistic):           1.34e-27
Time:                        11:37:50   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
R&D Spend           0.8060      0.046     17.369      0.000       0.712       0.900
Administration     -0.0270      0.052     -0.517      0.608      -0.132       0.078
Marketing Spend     0.0270      0.017      1.574      0.123      -0.008       0.062
1                 198.7888   3371.007      0.059      0.953   -6595.030    6992.607
2                 -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:
# Here we drop feature 1(dummy variable) because it has highest p value >0.05 so we drop it
x = x.drop(columns=[1])

In [24]:
x.head()

   const  R&D Spend  Administration  Marketing Spend    2
0    1.0  165349.20       136897.80        471784.10  1.0
1    1.0  162597.70       151377.59        443898.53  0.0
2    1.0  153441.51       101145.55        407934.54  0.0
3    1.0  144372.41       118671.85        383199.62  1.0
4    1.0  142107.34        91391.77        366168.42  0.0

In [25]:
# Fit OLS model
regressor_OLS =sm.OLS(y,x).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Fri, 16 Jul 2021   Prob (F-statistic):           8.50e-29
Time:                        11:39:47   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.018e+04   6747.623      7.437      0.000    3.66e+04    6.38e+04
R&D Spend           0.8059      0.046     17.571      0.000       0.714       0.898
Administration     -0.0269      0.052     -0.521      0.605      -0.131       0.077
Marketing Spend     0.0271      0.017      1.625      0.111      -0.007       0.061
2                -136.5042   2801.719     -0.049      0.961   -5779.456    5506.447
==============================================================================
Omnibus:                       14.892   Durbin-Watson:                   1.284
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.665
Skew:                          -0.949   Prob(JB):                     1.97e-05
Kurtosis:                       5.608   Cond. No.                     1.43e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [26]:
# Here we drop feature 2(dummy variable) because it has highest p value >0.05 so we drop it
x = x.drop(columns=[2])

In [27]:
x.head()

   const  R&D Spend  Administration  Marketing Spend
0    1.0  165349.20       136897.80        471784.10
1    1.0  162597.70       151377.59        443898.53
2    1.0  153441.51       101145.55        407934.54
3    1.0  144372.41       118671.85        383199.62
4    1.0  142107.34        91391.77        366168.42

In [28]:
# Fit OLS model
regressor_OLS =sm.OLS(y,x).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Fri, 16 Jul 2021   Prob (F-statistic):           4.53e-30
Time:                        11:41:56   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
R&D Spend           0.8057      0.045     17.846      0.000       0.715       0.897
Administration     -0.0268      0.051     -0.526      0.602      -0.130       0.076
Marketing Spend     0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
# Here we drop feature Administration(dummy variable) because it has highest p value >0.05 so we drop it
x = x.drop(columns=['Administration'])

In [31]:
x.head()

   const  R&D Spend  Marketing Spend
0    1.0  165349.20        471784.10
1    1.0  162597.70        443898.53
2    1.0  153441.51        407934.54
3    1.0  144372.41        383199.62
4    1.0  142107.34        366168.42

In [32]:
# Fit OLS model
regressor_OLS =sm.OLS(y,x).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Fri, 16 Jul 2021   Prob (F-statistic):           2.16e-31
Time:                        11:44:58   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
R&D Spend           0.7966      0.041     19.266      0.000       0.713       0.880
Marketing Spend     0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
# Here we drop feature Marketing Spend(dummy variable) because it has highest p value >0.05 so we drop it
x = x.drop(columns=['Marketing Spend'])

In [34]:
x.head()

   const  R&D Spend
0    1.0  165349.20
1    1.0  162597.70
2    1.0  153441.51
3    1.0  144372.41
4    1.0  142107.34

In [35]:
# Fit OLS model
regressor_OLS =sm.OLS(y,x).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Fri, 16 Jul 2021   Prob (F-statistic):           3.50e-32
Time:                        11:48:18   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
R&D Spend      0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [37]:
x.head()

   const  R&D Spend
0    1.0  165349.20
1    1.0  162597.70
2    1.0  153441.51
3    1.0  144372.41
4    1.0  142107.34

In [38]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

### After Back Elimination OR Multi Collinearity

#### Again we do modeling

In [39]:
# splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [40]:
# Fitting the MLR model to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [41]:
#Predicting the Test set results
y_pred = regressor.predict(x_test)

In [42]:
y_pred

array([104667.27805998, 134150.83410578, 135207.80019517,  72170.54428856,
       179090.58602508, 109824.77386586,  65644.27773757, 100481.43277139,
       111431.75202432, 169438.14843539])

In [43]:
# Checking the score
print('Train Score:',regressor.score(x_train,y_train))
print('Test Score:',regressor.score(x_test, y_test))

Train Score: 0.9449589778363044
Test Score: 0.9464587607787219